### ISSUE TITLE
Issue: Level Has Holes

### ISSUE THREAD

**Issue by pavlearezina** [lawlbit/GameNamePlaceHolder#164] opened 2019-01-11 04:10 UTC
![test](https://user-images.githubusercontent.com/15236969/51012771-d9e63d80-152c-11e9-904a-9df9f806d86c.PNG)

**Comment by SusanSuY** [comment] 2019-01-27 18:21
Duplicate of issue #106

**Closed by SusanSuY** 2019-01-27 18:21 UTC
Labels: duplicate
