### ISSUE TITLE
ISSUE: Players rotation is not shown correctly on another players screen

### ISSUE THREAD

**Issue by wildingelijah** [lawlbit/GameNamePlaceHolder#180] opened 2019-01-11 19:37 UTC
#### Context
Player 2 was spinning and their view direction was not accurately represented on my screen. 
#### Expected Output
Each player's view should be shown correctly on the other's screen.
#### Actual Output
Player's would either remain still when moving their view or be facing a different direction than they actually were on their screen.
### Steps to Reproduce
1. Run two instances
2. Spin character in instance 1.
3. Observe in instance 2.
### Bug Appearance
This happened everywhere in the level and I believe must be a network/connection bug rather than and actual client side bug.
### System Configuration
Resolution: Full screen
OS: Windows
Controller Type: Mouse & Keyboard

**Comment by lawlbit** [comment] 2019-03-12 17:17
This issue was caused by the delay of data transmission as well as the mixed interpolation of both rotation and angular velocity. This has been resolved by solely relying on rotation interpolation and ignoring angular velocity.

**Closed by lawlbit** 2019-03-12 17:17 UTC
Labels: P0: Urgent Priority, bug
