### ISSUE TITLE
Bug #4: When player 2 joins the match, the character stats are displayed as 0. 

### ISSUE THREAD

**Issue by TinkLyke** [lawlbit/GameNamePlaceHolder#58] opened 2018-12-21 02:36 UTC

**Comment by SusanSuY** [comment] 2019-02-20 06:25
**Root cause:** The stat allocations were being updated on the server correctly, but the update stat text function was being called too early before the information on networking finished sending.

**Solution:** Move updating of stat text to Update() function. Fixed in [c923b6e](https://github.com/lawlbit/GameNamePlaceHolder/commit/c923b6e8b7ab9ad944225b9c42a1d04b1e82f48d).

**Closed by SusanSuY** 2019-02-20 06:25 UTC
Labels: P1: High Priority, bug
