### ISSUE TITLE
Issue: Graphics Options Limited

### ISSUE THREAD

**Issue by pavlearezina** [lawlbit/GameNamePlaceHolder#157] opened 2019-01-11 03:18 UTC
Graphics Option only allows one screen resolution and one video settings which is high. Does not let user change the options to a lower quality or different resolution.

**Comment by sma7560** [comment] 2019-01-28 06:16
Dupe of #57

**Comment by sma7560** [comment] 2019-01-28 06:19
We will likely remove the in-game graphics menu.

**Comment by SusanSuY** [comment] 2019-03-14 22:13
In-game graphics menu has been removed in commit [09abbcd](https://github.com/lawlbit/GameNamePlaceHolder/commit/09abbcdd390f11980b536d3a49ca0725645b8dee)

**Closed by SusanSuY** 2019-03-14 22:13 UTC
Labels: P3: Low Priority
