### ISSUE TITLE
Issue #7: Cannot move to corner of tiles on diagonal hallways.

### ISSUE THREAD

**Issue by NathanCoit** [lawlbit/GameNamePlaceHolder#124] opened 2019-01-08 19:45 UTC
The bottom right half of the tile cannot be walked on.

![image](https://user-images.githubusercontent.com/26461233/50854827-275b8280-1354-11e9-8b03-ca6d1aa46697.png)

**Comment by SusanSuY** [comment] 2019-01-29 01:18
Duplicate of issue #65 . Also see issue #84

**Closed by SusanSuY** 2019-01-29 01:18 UTC
Labels: duplicate
