### ISSUE TITLE
Issue: 2nd Player's stat distribution doesn't add or subtract properly. 

### ISSUE THREAD

**Issue by nicolaikozel** [lawlbit/GameNamePlaceHolder#133] opened 2019-01-08 20:14 UTC
Following this issue - https://github.com/lawlbit/GameNamePlaceHolder/issues/103#issue-395370462.
As David mentions, the stats reset from 0 to the default numbers after trying to add one but then the adding and subtracting doesn't work. (Adding will subtract, and subtracting will add).

**Comment by SusanSuY** [comment] 2019-01-28 17:08
Duplicate of issues #58 , #59

**Closed by SusanSuY** 2019-01-28 17:08 UTC
Labels: P1: High Priority
