### ISSUE TITLE
Issue: Objectives do not complete and are not updated.

### ISSUE THREAD

**Issue by nicolaikozel** [lawlbit/GameNamePlaceHolder#135] opened 2019-01-08 20:28 UTC
After defeating a minion, the total does go down/there is not indication that progress has been made towards this objective. The objective for defeating another player does not complete after successfully killing another player.

**Comment by sma7560** [comment] 2019-01-28 05:50
Dupe of #67

**Closed by sma7560** 2019-01-28 05:50 UTC
Labels: P2: Medium Priority, duplicate
