### ISSUE TITLE
ISSUE: Game Over screen appears and cannot be exited

### ISSUE THREAD

**Issue by KarnvirBining** [lawlbit/GameNamePlaceHolder#87] opened 2018-12-26 00:02 UTC
When creating a new game, if a game already exists with the current IP then the second instance of the game is terminated and a game over screen appears with a "Main Menu" button that does nothing. Nothing can be done with that second game now. 

Steps to reproduce:
1. Open 2 instances of TPK on the same IP
2. In the first instance: Start Game -> New Game -> Create Dungeon
3. Then in the second instance: Start Game -> New Game -> Create Dungeon
4. Second instance should now have a Game Over Screen overlay player 1 and player 2 scores (both 20) and says "Player 1 Wins"

**Comment by SusanSuY** [comment] 2019-02-19 22:40
**Root cause:** the second game's MatchManager was created, but could not be properly initialized since it failed to connect to network as the server since the server already exists on the network (the first game). Thus, the match time left in second game's MatchManager is 0 seconds, leading to it thinking that the game ended. Thus, a local scoreboard popped up in second game, and game became soft locked.

This has been fixed in commit [63fe47b](https://github.com/lawlbit/GameNamePlaceHolder/commit/63fe47bd5fd779b8c8c43f8c927bcd2f5a6eefc8). Instead, we now ask the server to do a ClientRpc call to initiate scoreboard on all clients when the match ends. Therefore, scoreboard can no longer pop up locally, and must be done through the server.

**Closed by SusanSuY** 2019-02-19 22:40 UTC
Labels: P0: Urgent Priority, bug
