### ISSUE TITLE
ISSUE: Game Over Screen Appears After Game While In Main Menu

### ISSUE THREAD

**Issue by David-Hobson** [lawlbit/GameNamePlaceHolder#100] opened 2019-01-02 20:14 UTC
The Game Over screen appeared much later after the game had ended. Screen shot below:
![image](https://user-images.githubusercontent.com/15710591/50610414-e6b9c000-0ea0-11e9-93f6-f19584df70f4.png)

**Comment by David-Hobson** [comment] 2019-01-02 20:24
UPDATE: This seems to happen when two people choose to create a dungeon on the same computer. The second person to create a dungeon will have this menu pop up, and will soft lock the game.

**Comment by SusanSuY** [comment] 2019-01-28 17:00
Similar to #87 , but we will also need to look into the issue of it appearing late after the game ended.

**Comment by SusanSuY** [comment] 2019-02-19 22:42
Issue of two games trying to start new game is fixed in [63fe47b](https://github.com/lawlbit/GameNamePlaceHolder/commit/63fe47bd5fd779b8c8c43f8c927bcd2f5a6eefc8). Also see comment in issue #87 for details on the root cause/fix.

Cannot reproduce the scoreboard showing up late after a match has ended. Thus, closing this issue.

**Closed by SusanSuY** 2019-02-19 22:42 UTC
Labels: P2: Medium Priority, bug
