### ISSUE TITLE
ISSUE #1: Creating new dungeon while one already exists breaks game

### ISSUE THREAD

**Issue by JohnnyEndrizzi** [lawlbit/GameNamePlaceHolder#107] opened 2019-01-07 04:04 UTC
Create Dungeon in a second window, while first window is waiting for players, pops up game over menu and freezes the second game (first window is unaffected)

**Comment by SusanSuY** [comment] 2019-01-28 17:02
Duplicate of issue #87

**Closed by SusanSuY** 2019-01-28 17:02 UTC
